style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/syntro-opensource/silverstripe-elemental-video
options:
  commits:
    filters:
      Type:
        - add
        - fix
        - change
        - remove
        - deprecate
        - Bump
        - Update
  commit_groups:
    title_maps:
      add: 🍰 Added
      fix: 🐞 Fixed
      change: 🔧 Changed
      deprecate: 💀 Deprecated
      remove: 🗑 Removed
      Bump: 🧬 Dependencies
      Update: 🧬 Composer Dependencies
  header:
    pattern: "^(\\w*)\\:?\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
